#!/bin/sh

CLOCK_FILE="/boot/clock"
CLOCK_CMD="/boot/clock_cmd.sh"

start() {
	echo "Setting up clock configuration"
	mkdir /boot
	mount -r /dev/mmcblk0p1 /boot
	if [ -e "$CLOCK_FILE" ]; then
                echo "Copying clock binary"
                mkdir -p /root
                cp $TALLY_FILE /root/rpi-matrix/clock
		chmod a+x /root/rpi-matrix/clock
        fi
	if [ -e "$CLOCK_CMD" ]; then
		echo "Copying clock configuration"
		mkdir -p /root
		cp $TALLY_CMD /root/rpi-matrix/clock_cmd.sh
		chmod a+x /root/rpi-matrix/clock_cmd.sh
	fi
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
